CREATE TABLE gen(
  id BIGSERIAL PRIMARY KEY,
  ensembl_ID varchar(255),
  gene_Ensembl varchar(255),
  gene_biotype varchar(255),
  G146_ctr_H double precision,
  G146_ctr double precision,
  G146_treat_H double precision,
  G146_treat double precision,
  G34_ctr_H double precision,
  G34_ctr double precision,
  G34_treat_H double precision,
  G34_treat double precision,
  G44_ctr_H double precision,
  G44_ctr double precision,
  G44_treat_H double precision,
  G44_treat double precision,
  G62_ctr_H double precision,
  G62_ctr double precision,
  G62_treat_H double precision,
  G62_treat double precision,
  G88_ctr_H double precision,
  G88_ctr double precision,
  G88_treat_H double precision,
  G88_treat double precision
);